Improve usability
NwangwuOsitadinma/gateman pull request #11
Opened 2020-04-06 22:47 UTC by Valentine-Mario

2020-04-11 11:10 UTC, ibesoft11 requested changes
This PR doesn't fully address the issue of inconsistency with error messages.
I suggest errors should be of this format `{ error: 'description|mongooseErrorObject', type: 'mongoose|gateman' }` to ease debugging for developers.
@NwangwuOsitadinma your thoughts?

2020-04-15 10:12 UTC, ibesoft11 approved these changes

2020-04-25 15:06 UTC, NwangwuOsitadinma approved these changes
Good enough.

2020-04-25 15:07 UTC, NwangwuOsitadinma commented
This works better

2020-04-25 15:07 UTC, closed without merging